### PR TITLE
Validate cookie name 

### LINKED ISSUE #264: No errors logged when Set-cookie header is not sent in response due to an invalid cookie
oauth2_proxy currently will silently fail to complete authentication if an invalid cookie name is set, perpetually redirecting the user back to the login screen with no errors logged.

This seems to be due to the behavior of Go's http.SetCookie method which according to the docs: ` The provided cookie must have a valid Name. Invalid cookies may be silently dropped.`. Since oauth2_proxy's authentication relies on setting a cookie, there should be validation that the `MakeCookie` method makes a valid cookie, and subsequently, that the Set-Cookie header is actually included in the response headers.

### PR DESCRIPTION
**Pull request by tanuck**
This fixes #264 

`(http.Cookie).String()` will silently return an empty string when the cookie name contains a rune not in the following table https://github.com/golang/net/blob/master/lex/httplex/httplex.go#L17

With this patch I've added an additional validator to check the cookie name at boot. I've had to 'mock' a `http.Cookie` as the http package doesn't export the check function, here: https://github.com/golang/go/blob/master/src/net/http/cookie.go#L368

Regards,
James

### CODE REVIEW

**Comment by ploxiln** [comment]
Not a bad idea.

Unrelated quick tip: your links are broken. It's because you used the "Add a link" button in the github comment editor, and pasted the url into the title part (between `[]`) and left the url part blank (between `()`). Anyway, you can just paste the link in without anything special and it will do as you expect.

**Comment by tanuck** [comment]
@ploxiln thanks for spotting that. Should have double checked...

File: options.go [hunk 1]
```diff
@@ -261,6 +263,14 @@ func parseSignatureKey(o *Options, msgs []string) []string {
 	return msgs
 }
 
+func validateCookieName(o *Options, msgs []string) []string {
+	cookie := &http.Cookie{Name: o.CookieName}
+	if cookie.String() == "" {
+		return append(msgs, "invalid cookie name: "+o.CookieName)
```
Comment (jehiah) [inline options.go]: Can you use `fmt.Sprintf` verb `%q` here?

**Comment by jehiah** [comment]
@tanuck thanks for your contribution. I just had one small comment before we merge this

File: options.go (hunk 1 above)
Comment (tanuck) [inline options.go]: Yeah sure... Should the usage me made a bit more consistent? I.e `func parseSignatureKey` uses concatenation, whereas others use `fmt.Sprintf`?

Comment (jehiah) [inline options.go]: Let's leave this PR scoped to this message.  

concatenation is "OK" (it's not going to panic or anything) it's just that when the purpose of an error is to highlight unusual values (like a null byte, or a `\r`) `%q` can greatly clarify things vs `%s`.
